
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ModuleManager.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Competentie
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Competentie()
    {

        this.ModuleCompetenties = new HashSet<ModuleCompetentie>();

    }


    public string Code { get; set; }

    public string Schooljaar { get; set; }

    public string Naam { get; set; }

    public string Beschrijving { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ModuleCompetentie> ModuleCompetenties { get; set; }

}

}
