//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaseModule
    {
        public string FaseNaam { get; set; }
        public string ModuleCursusCode { get; set; }
        public string ModuleSchooljaar { get; set; }
    
        public virtual Fase Fase { get; set; }
        public virtual Module Module { get; set; }
    }
}
