//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kwaliteitskenmerk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kwaliteitskenmerk()
        {
            this.Leerdoelen = new HashSet<Leerdoel>();
        }
    
        public int Id { get; set; }
        public int CompetentieOnderdeelId { get; set; }
        public int Volgnummer { get; set; }
        public string Omschrijving { get; set; }
    
        public virtual CompetentieOnderdeel CompetentieOnderdeel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leerdoel> Leerdoelen { get; set; }
    }
}
