//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DomainEntities : DbContext
    {
        public DomainEntities()
            : base("name=DomainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blok> Bloks { get; set; }
        public virtual DbSet<Competentie> Competenties { get; set; }
        public virtual DbSet<FaseType> FaseTypes { get; set; }
        public virtual DbSet<Leerlijn> Leerlijnen { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleCompetentie> ModuleCompetenties { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<Onderdeel> Onderdeels { get; set; }
        public virtual DbSet<Opleiding> Opleidings { get; set; }
        public virtual DbSet<Schooljaar> Schooljaars { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StudieBelasting> StudieBelastings { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Toetsvorm> Toetsvorms { get; set; }
        public virtual DbSet<Weekplanning> Weekplannings { get; set; }
        public virtual DbSet<Werkvorm> Werkvormen { get; set; }
        public virtual DbSet<Fase> Fases { get; set; }
        public virtual DbSet<Docent> Docenten { get; set; }
        public virtual DbSet<Beoordeling> Beoordelingen { get; set; }
        public virtual DbSet<Leerdoel> Leerdoelen { get; set; }
        public virtual DbSet<Leermiddel> Leermiddelen { get; set; }
        public virtual DbSet<StudiePunt> StudiePunten { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<ModuleWerkvorm> ModuleWerkvormen { get; set; }
    }
}
