//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DomainDalEntities : DbContext
    {
        public DomainDalEntities()
            : base("name=DomainDalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beoordelingen> Beoordelingens { get; set; }
        public virtual DbSet<Blok> Bloks { get; set; }
        public virtual DbSet<Competentie> Competenties { get; set; }
        public virtual DbSet<Docenten> Docentens { get; set; }
        public virtual DbSet<FaseType> FaseTypes { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<Leerdoelen> Leerdoelens { get; set; }
        public virtual DbSet<Leerlijn> Leerlijns { get; set; }
        public virtual DbSet<Leermiddelen> Leermiddelens { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleCompetentie> ModuleCompetenties { get; set; }
        public virtual DbSet<ModuleWerkvorm> ModuleWerkvorms { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<Onderdeel> Onderdeels { get; set; }
        public virtual DbSet<Opleiding> Opleidings { get; set; }
        public virtual DbSet<Schooljaar> Schooljaars { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StudieBelasting> StudieBelastings { get; set; }
        public virtual DbSet<StudiePunten> StudiePuntens { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Toetsvorm> Toetsvorms { get; set; }
        public virtual DbSet<Weekplanning> Weekplannings { get; set; }
        public virtual DbSet<Werkvorm> Werkvorms { get; set; }
        public virtual DbSet<Fase> Fases { get; set; }
        public virtual DbSet<FaseModule> FaseModules { get; set; }
    }
}
